#!/bin/sh
make clean
make doxygen
cd docs
make clean
mkdir -p _build/html
cd _build
git clone -b gh-pages git@github.com:lanice/hyrise.git html
cd ..
make html
cd _build/html
git add .
git commit -am 'Updating docs'
git push origin gh-pages