#!/bin/bash

OPTIONS="-y --no-install-recommends -q"

# delete Error log, if it exists
rm packageErr.log 2>/dev/null

sudo apt-get $OPTIONS install accountsservice 2>>packageErr.log
sudo apt-get $OPTIONS install adduser 2>>packageErr.log
sudo apt-get $OPTIONS install anthy 2>>packageErr.log
sudo apt-get $OPTIONS install anthy-common 2>>packageErr.log
sudo apt-get $OPTIONS install antlr 2>>packageErr.log
sudo apt-get $OPTIONS install apparmor 2>>packageErr.log
sudo apt-get $OPTIONS install apport 2>>packageErr.log
sudo apt-get $OPTIONS install apport-symptoms 2>>packageErr.log
sudo apt-get $OPTIONS install apt 2>>packageErr.log
sudo apt-get $OPTIONS install apt-transport-https 2>>packageErr.log
sudo apt-get $OPTIONS install apt-utils 2>>packageErr.log
sudo apt-get $OPTIONS install apt-xapian-index 2>>packageErr.log
sudo apt-get $OPTIONS install aptitude 2>>packageErr.log
sudo apt-get $OPTIONS install at 2>>packageErr.log
sudo apt-get $OPTIONS install base-files 2>>packageErr.log
sudo apt-get $OPTIONS install base-passwd 2>>packageErr.log
sudo apt-get $OPTIONS install bash 2>>packageErr.log
sudo apt-get $OPTIONS install bash-completion 2>>packageErr.log
sudo apt-get $OPTIONS install bb 2>>packageErr.log
sudo apt-get $OPTIONS install bc 2>>packageErr.log
sudo apt-get $OPTIONS install bind9-host 2>>packageErr.log
sudo apt-get $OPTIONS install binutils 2>>packageErr.log
sudo apt-get $OPTIONS install bsdmainutils 2>>packageErr.log
sudo apt-get $OPTIONS install bsdutils 2>>packageErr.log
sudo apt-get $OPTIONS install build-essential 2>>packageErr.log
sudo apt-get $OPTIONS install busybox-initramfs 2>>packageErr.log
sudo apt-get $OPTIONS install busybox-static 2>>packageErr.log
sudo apt-get $OPTIONS install byobu 2>>packageErr.log
sudo apt-get $OPTIONS install bzip2 2>>packageErr.log
sudo apt-get $OPTIONS install ca-certificates 2>>packageErr.log
sudo apt-get $OPTIONS install ca-certificates-java 2>>packageErr.log
sudo apt-get $OPTIONS install ccache 2>>packageErr.log
sudo apt-get $OPTIONS install cmake 2>>packageErr.log
sudo apt-get $OPTIONS install cmake-data 2>>packageErr.log
sudo apt-get $OPTIONS install cmap-adobe-japan1 2>>packageErr.log
sudo apt-get $OPTIONS install comerr-dev 2>>packageErr.log
sudo apt-get $OPTIONS install command-not-found 2>>packageErr.log
sudo apt-get $OPTIONS install command-not-found-data 2>>packageErr.log
sudo apt-get $OPTIONS install console-setup 2>>packageErr.log
sudo apt-get $OPTIONS install coreutils 2>>packageErr.log
sudo apt-get $OPTIONS install cpio 2>>packageErr.log
sudo apt-get $OPTIONS install cpp 2>>packageErr.log
sudo apt-get $OPTIONS install cpp-4.6 2>>packageErr.log
sudo apt-get $OPTIONS install cron 2>>packageErr.log
sudo apt-get $OPTIONS install dash 2>>packageErr.log
sudo apt-get $OPTIONS install dbus 2>>packageErr.log
sudo apt-get $OPTIONS install debconf 2>>packageErr.log
sudo apt-get $OPTIONS install debconf-i18n 2>>packageErr.log
sudo apt-get $OPTIONS install debianutils 2>>packageErr.log
sudo apt-get $OPTIONS install default-jre-headless 2>>packageErr.log
sudo apt-get $OPTIONS install defoma 2>>packageErr.log
sudo apt-get $OPTIONS install dictionaries-common 2>>packageErr.log
sudo apt-get $OPTIONS install diffutils 2>>packageErr.log
sudo apt-get $OPTIONS install distcc 2>>packageErr.log
sudo apt-get $OPTIONS install distcc-pump 2>>packageErr.log
sudo apt-get $OPTIONS install dmidecode 2>>packageErr.log
sudo apt-get $OPTIONS install dmsetup 2>>packageErr.log
sudo apt-get $OPTIONS install dnsutils 2>>packageErr.log
sudo apt-get $OPTIONS install doc-base 2>>packageErr.log
sudo apt-get $OPTIONS install dosfstools 2>>packageErr.log
sudo apt-get $OPTIONS install doxygen 2>>packageErr.log
sudo apt-get $OPTIONS install doxygen-latex 2>>packageErr.log
sudo apt-get $OPTIONS install dpkg 2>>packageErr.log
sudo apt-get $OPTIONS install dpkg-dev 2>>packageErr.log
sudo apt-get $OPTIONS install e2fslibs 2>>packageErr.log
sudo apt-get $OPTIONS install e2fsprogs 2>>packageErr.log
sudo apt-get $OPTIONS install ed 2>>packageErr.log
sudo apt-get $OPTIONS install eject 2>>packageErr.log
sudo apt-get $OPTIONS install emacs 2>>packageErr.log
sudo apt-get $OPTIONS install emacs23 2>>packageErr.log
sudo apt-get $OPTIONS install emacs23-bin-common 2>>packageErr.log
sudo apt-get $OPTIONS install emacs23-common 2>>packageErr.log
sudo apt-get $OPTIONS install emacsen-common 2>>packageErr.log
sudo apt-get $OPTIONS install fakeroot 2>>packageErr.log
sudo apt-get $OPTIONS install file 2>>packageErr.log
sudo apt-get $OPTIONS install findutils 2>>packageErr.log
sudo apt-get $OPTIONS install firefox-locale-en 2>>packageErr.log
sudo apt-get $OPTIONS install fontconfig 2>>packageErr.log
sudo apt-get $OPTIONS install fontconfig-config 2>>packageErr.log
sudo apt-get $OPTIONS install friendly-recovery 2>>packageErr.log
sudo apt-get $OPTIONS install ftp 2>>packageErr.log
sudo apt-get $OPTIONS install fuse-utils 2>>packageErr.log
sudo apt-get $OPTIONS install g++ 2>>packageErr.log
sudo apt-get $OPTIONS install g++-4.6 2>>packageErr.log
sudo apt-get $OPTIONS install gcc 2>>packageErr.log
sudo apt-get $OPTIONS install gcc-4.6 2>>packageErr.log
sudo apt-get $OPTIONS install gcc-4.6-base 2>>packageErr.log
sudo apt-get $OPTIONS install gconf2-common 2>>packageErr.log
sudo apt-get $OPTIONS install gdb 2>>packageErr.log
sudo apt-get $OPTIONS install geoip-database 2>>packageErr.log
sudo apt-get $OPTIONS install gettext-base 2>>packageErr.log
sudo apt-get $OPTIONS install ghostscript 2>>packageErr.log
sudo apt-get $OPTIONS install ghostscript-x 2>>packageErr.log
sudo apt-get $OPTIONS install gir1.2-glib-2.0 2>>packageErr.log
sudo apt-get $OPTIONS install git 2>>packageErr.log
sudo apt-get $OPTIONS install git-man 2>>packageErr.log
sudo apt-get $OPTIONS install gnupg 2>>packageErr.log
sudo apt-get $OPTIONS install gnuplot 2>>packageErr.log
sudo apt-get $OPTIONS install gnuplot-nox 2>>packageErr.log
sudo apt-get $OPTIONS install gnuplot-x11 2>>packageErr.log
sudo apt-get $OPTIONS install gpgv 2>>packageErr.log
sudo apt-get $OPTIONS install graphviz 2>>packageErr.log
sudo apt-get $OPTIONS install grep 2>>packageErr.log
sudo apt-get $OPTIONS install groff 2>>packageErr.log
sudo apt-get $OPTIONS install groff-base 2>>packageErr.log
sudo apt-get $OPTIONS install grub-common 2>>packageErr.log
sudo apt-get $OPTIONS install grub-gfxpayload-lists 2>>packageErr.log
sudo apt-get $OPTIONS install grub-pc 2>>packageErr.log
sudo apt-get $OPTIONS install grub-pc-bin 2>>packageErr.log
sudo apt-get $OPTIONS install grub2-common 2>>packageErr.log
sudo apt-get $OPTIONS install gs-cjk-resource 2>>packageErr.log
sudo apt-get $OPTIONS install gsfonts 2>>packageErr.log
sudo apt-get $OPTIONS install gv 2>>packageErr.log
sudo apt-get $OPTIONS install gzip 2>>packageErr.log
sudo apt-get $OPTIONS install hdparm 2>>packageErr.log
sudo apt-get $OPTIONS install hicolor-icon-theme 2>>packageErr.log
sudo apt-get $OPTIONS install hostname 2>>packageErr.log
sudo apt-get $OPTIONS install iamerican 2>>packageErr.log
sudo apt-get $OPTIONS install icecc 2>>packageErr.log
sudo apt-get $OPTIONS install icedtea-6-jre-cacao 2>>packageErr.log
sudo apt-get $OPTIONS install icedtea-6-jre-jamvm 2>>packageErr.log
sudo apt-get $OPTIONS install ienglish-common 2>>packageErr.log
sudo apt-get $OPTIONS install ifupdown 2>>packageErr.log
sudo apt-get $OPTIONS install imagemagick 2>>packageErr.log
sudo apt-get $OPTIONS install info 2>>packageErr.log
sudo apt-get $OPTIONS install initramfs-tools 2>>packageErr.log
sudo apt-get $OPTIONS install initramfs-tools-bin 2>>packageErr.log
sudo apt-get $OPTIONS install initscripts 2>>packageErr.log
sudo apt-get $OPTIONS install insserv 2>>packageErr.log
sudo apt-get $OPTIONS install install-info 2>>packageErr.log
sudo apt-get $OPTIONS install installation-report 2>>packageErr.log
sudo apt-get $OPTIONS install iproute 2>>packageErr.log
sudo apt-get $OPTIONS install iptables 2>>packageErr.log
sudo apt-get $OPTIONS install iputils-ping 2>>packageErr.log
sudo apt-get $OPTIONS install iputils-tracepath 2>>packageErr.log
sudo apt-get $OPTIONS install irqbalance 2>>packageErr.log
sudo apt-get $OPTIONS install isc-dhcp-client 2>>packageErr.log
sudo apt-get $OPTIONS install isc-dhcp-common 2>>packageErr.log
sudo apt-get $OPTIONS install iso-codes 2>>packageErr.log
sudo apt-get $OPTIONS install ispell 2>>packageErr.log
sudo apt-get $OPTIONS install java-common 2>>packageErr.log
sudo apt-get $OPTIONS install kbd 2>>packageErr.log
sudo apt-get $OPTIONS install keyboard-configuration 2>>packageErr.log
sudo apt-get $OPTIONS install klibc-utils 2>>packageErr.log
sudo apt-get $OPTIONS install krb5-multidev 2>>packageErr.log
sudo apt-get $OPTIONS install lacheck 2>>packageErr.log
sudo apt-get $OPTIONS install landscape-common 2>>packageErr.log
sudo apt-get $OPTIONS install language-pack-en 2>>packageErr.log
sudo apt-get $OPTIONS install language-pack-en-base 2>>packageErr.log
sudo apt-get $OPTIONS install language-pack-gnome-en 2>>packageErr.log
sudo apt-get $OPTIONS install language-pack-gnome-en-base 2>>packageErr.log
sudo apt-get $OPTIONS install language-selector-common 2>>packageErr.log
sudo apt-get $OPTIONS install laptop-detect 2>>packageErr.log
sudo apt-get $OPTIONS install latex-beamer 2>>packageErr.log
sudo apt-get $OPTIONS install latex-xcolor 2>>packageErr.log
sudo apt-get $OPTIONS install less 2>>packageErr.log
sudo apt-get $OPTIONS install libaa1 2>>packageErr.log
sudo apt-get $OPTIONS install libaccountsservice0 2>>packageErr.log
sudo apt-get $OPTIONS install libacl1 2>>packageErr.log
sudo apt-get $OPTIONS install libalgorithm-diff-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libalgorithm-diff-xs-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libalgorithm-merge-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libanthy0 2>>packageErr.log
sudo apt-get $OPTIONS install libantlr-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libantlr-java 2>>packageErr.log
sudo apt-get $OPTIONS install libantlr3c-3.2-0 2>>packageErr.log
sudo apt-get $OPTIONS install libantlr3c-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libapr1 2>>packageErr.log
sudo apt-get $OPTIONS install libapr1-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libaprutil1 2>>packageErr.log
sudo apt-get $OPTIONS install libaprutil1-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libapt-inst1.3 2>>packageErr.log
sudo apt-get $OPTIONS install libapt-pkg4.11 2>>packageErr.log
sudo apt-get $OPTIONS install libarchive1 2>>packageErr.log
sudo apt-get $OPTIONS install libasound2 2>>packageErr.log
sudo apt-get $OPTIONS install libatk1.0-0 2>>packageErr.log
sudo apt-get $OPTIONS install libatk1.0-data 2>>packageErr.log
sudo apt-get $OPTIONS install libattr1 2>>packageErr.log
sudo apt-get $OPTIONS install libavahi-client3 2>>packageErr.log
sudo apt-get $OPTIONS install libavahi-common-data 2>>packageErr.log
sudo apt-get $OPTIONS install libavahi-common3 2>>packageErr.log
sudo apt-get $OPTIONS install libbind9-60 2>>packageErr.log
sudo apt-get $OPTIONS install libblkid1 2>>packageErr.log
sudo apt-get $OPTIONS install libboost-date-time1.46-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libboost-date-time1.46.1 2>>packageErr.log
sudo apt-get $OPTIONS install libboost-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libboost-filesystem1.46-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libboost-filesystem1.46.1 2>>packageErr.log
sudo apt-get $OPTIONS install libboost-iostreams1.46.1 2>>packageErr.log
sudo apt-get $OPTIONS install libboost-program-options1.46-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libboost-program-options1.46.1 2>>packageErr.log
sudo apt-get $OPTIONS install libboost-serialization1.46-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libboost-serialization1.46.1 2>>packageErr.log
sudo apt-get $OPTIONS install libboost-system1.46-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libboost-system1.46.1 2>>packageErr.log
sudo apt-get $OPTIONS install libboost-thread1.46-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libboost-thread1.46.1 2>>packageErr.log
sudo apt-get $OPTIONS install libboost1.46-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libbsd0 2>>packageErr.log
sudo apt-get $OPTIONS install libbz2-1.0 2>>packageErr.log
sudo apt-get $OPTIONS install libc-bin 2>>packageErr.log
sudo apt-get $OPTIONS install libc-dev-bin 2>>packageErr.log
sudo apt-get $OPTIONS install libc6 2>>packageErr.log
sudo apt-get $OPTIONS install libc6-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libcairo2 2>>packageErr.log
sudo apt-get $OPTIONS install libcap-ng0 2>>packageErr.log
sudo apt-get $OPTIONS install libcdt4 2>>packageErr.log
sudo apt-get $OPTIONS install libcgraph5 2>>packageErr.log
sudo apt-get $OPTIONS install libclass-accessor-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libclass-isa-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libcomerr2 2>>packageErr.log
sudo apt-get $OPTIONS install libcroco3 2>>packageErr.log
sudo apt-get $OPTIONS install libcups2 2>>packageErr.log
sudo apt-get $OPTIONS install libcupsimage2 2>>packageErr.log
sudo apt-get $OPTIONS install libcurl3 2>>packageErr.log
sudo apt-get $OPTIONS install libcurl3-gnutls 2>>packageErr.log
sudo apt-get $OPTIONS install libcwidget3 2>>packageErr.log
sudo apt-get $OPTIONS install libdatrie1 2>>packageErr.log
sudo apt-get $OPTIONS install libdb4.8 2>>packageErr.log
sudo apt-get $OPTIONS install libdb5.1 2>>packageErr.log
sudo apt-get $OPTIONS install libdbd-mysql-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libdbi-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libdbus-1-3 2>>packageErr.log
sudo apt-get $OPTIONS install libdbus-glib-1-2 2>>packageErr.log
sudo apt-get $OPTIONS install libdevmapper-event1.02.1 2>>packageErr.log
sudo apt-get $OPTIONS install libdevmapper1.02.1 2>>packageErr.log
sudo apt-get $OPTIONS install libdjvulibre-text 2>>packageErr.log
sudo apt-get $OPTIONS install libdjvulibre21 2>>packageErr.log
sudo apt-get $OPTIONS install libdns69 2>>packageErr.log
sudo apt-get $OPTIONS install libdpkg-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libdrm-intel1 2>>packageErr.log
sudo apt-get $OPTIONS install libdrm-nouveau1a 2>>packageErr.log
sudo apt-get $OPTIONS install libdrm-radeon1 2>>packageErr.log
sudo apt-get $OPTIONS install libdrm2 2>>packageErr.log
sudo apt-get $OPTIONS install libedit2 2>>packageErr.log
sudo apt-get $OPTIONS install libelf1 2>>packageErr.log
sudo apt-get $OPTIONS install libept1 2>>packageErr.log
sudo apt-get $OPTIONS install liberror-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libev-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libev4 2>>packageErr.log
sudo apt-get $OPTIONS install libevent-2.0-5 2>>packageErr.log
sudo apt-get $OPTIONS install libexpat1 2>>packageErr.log
sudo apt-get $OPTIONS install libexpat1-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libffi6 2>>packageErr.log
sudo apt-get $OPTIONS install libfontconfig1 2>>packageErr.log
sudo apt-get $OPTIONS install libfontenc1 2>>packageErr.log
sudo apt-get $OPTIONS install libfreetype6 2>>packageErr.log
sudo apt-get $OPTIONS install libfribidi0 2>>packageErr.log
sudo apt-get $OPTIONS install libfuse2 2>>packageErr.log
sudo apt-get $OPTIONS install libgc1c2 2>>packageErr.log
sudo apt-get $OPTIONS install libgcc1 2>>packageErr.log
sudo apt-get $OPTIONS install libgconf2-4 2>>packageErr.log
sudo apt-get $OPTIONS install libgcrypt11 2>>packageErr.log
sudo apt-get $OPTIONS install libgd2-noxpm 2>>packageErr.log
sudo apt-get $OPTIONS install libgdbm3 2>>packageErr.log
sudo apt-get $OPTIONS install libgdk-pixbuf2.0-0 2>>packageErr.log
sudo apt-get $OPTIONS install libgeoip1 2>>packageErr.log
sudo apt-get $OPTIONS install libgif4 2>>packageErr.log
sudo apt-get $OPTIONS install libgirepository-1.0-1 2>>packageErr.log
sudo apt-get $OPTIONS install libgl1-mesa-dri 2>>packageErr.log
sudo apt-get $OPTIONS install libgl1-mesa-glx 2>>packageErr.log
sudo apt-get $OPTIONS install libglapi-mesa 2>>packageErr.log
sudo apt-get $OPTIONS install libglib2.0-0 2>>packageErr.log
sudo apt-get $OPTIONS install libgmp10 2>>packageErr.log
sudo apt-get $OPTIONS install libgnutls26 2>>packageErr.log
sudo apt-get $OPTIONS install libgomp1 2>>packageErr.log
sudo apt-get $OPTIONS install libgoogle-perftools-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libgoogle-perftools0 2>>packageErr.log
sudo apt-get $OPTIONS install libgpg-error0 2>>packageErr.log
sudo apt-get $OPTIONS install libgpm2 2>>packageErr.log
sudo apt-get $OPTIONS install libgraph4 2>>packageErr.log
sudo apt-get $OPTIONS install libgs9 2>>packageErr.log
sudo apt-get $OPTIONS install libgs9-common 2>>packageErr.log
sudo apt-get $OPTIONS install libgssapi-krb5-2 2>>packageErr.log
sudo apt-get $OPTIONS install libgssrpc4 2>>packageErr.log
sudo apt-get $OPTIONS install libgstreamer-plugins-base0.10-0 2>>packageErr.log
sudo apt-get $OPTIONS install libgstreamer0.10-0 2>>packageErr.log
sudo apt-get $OPTIONS install libgtk2.0-0 2>>packageErr.log
sudo apt-get $OPTIONS install libgtk2.0-bin 2>>packageErr.log
sudo apt-get $OPTIONS install libgtk2.0-common 2>>packageErr.log
sudo apt-get $OPTIONS install libgvc5 2>>packageErr.log
sudo apt-get $OPTIONS install libgvpr1 2>>packageErr.log
sudo apt-get $OPTIONS install libhtml-template-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libhwloc-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libhwloc3 2>>packageErr.log
sudo apt-get $OPTIONS install libice6 2>>packageErr.log
sudo apt-get $OPTIONS install libidn11 2>>packageErr.log
sudo apt-get $OPTIONS install libijs-0.35 2>>packageErr.log
sudo apt-get $OPTIONS install libilmbase6 2>>packageErr.log
sudo apt-get $OPTIONS install libio-string-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libisc62 2>>packageErr.log
sudo apt-get $OPTIONS install libisccc60 2>>packageErr.log
sudo apt-get $OPTIONS install libisccfg62 2>>packageErr.log
sudo apt-get $OPTIONS install libiw30 2>>packageErr.log
sudo apt-get $OPTIONS install libjasper1 2>>packageErr.log
sudo apt-get $OPTIONS install libjbig2dec0 2>>packageErr.log
sudo apt-get $OPTIONS install libjpeg62 2>>packageErr.log
sudo apt-get $OPTIONS install libjs-jquery 2>>packageErr.log
sudo apt-get $OPTIONS install libk5crypto3 2>>packageErr.log
sudo apt-get $OPTIONS install libkadm5clnt-mit8 2>>packageErr.log
sudo apt-get $OPTIONS install libkadm5srv-mit8 2>>packageErr.log
sudo apt-get $OPTIONS install libkdb5-5 2>>packageErr.log
sudo apt-get $OPTIONS install libkeyutils1 2>>packageErr.log
sudo apt-get $OPTIONS install libklibc 2>>packageErr.log
sudo apt-get $OPTIONS install libkpathsea5 2>>packageErr.log
sudo apt-get $OPTIONS install libkrb5-3 2>>packageErr.log
sudo apt-get $OPTIONS install libkrb5-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libkrb5support0 2>>packageErr.log
sudo apt-get $OPTIONS install liblcms1 2>>packageErr.log
sudo apt-get $OPTIONS install libldap-2.4-2 2>>packageErr.log
sudo apt-get $OPTIONS install libldap2-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libllvm2.9 2>>packageErr.log
sudo apt-get $OPTIONS install liblocale-gettext-perl 2>>packageErr.log
sudo apt-get $OPTIONS install liblockfile1 2>>packageErr.log
sudo apt-get $OPTIONS install liblog4cxx10 2>>packageErr.log
sudo apt-get $OPTIONS install liblog4cxx10-dev 2>>packageErr.log
sudo apt-get $OPTIONS install liblqr-1-0 2>>packageErr.log
sudo apt-get $OPTIONS install libltdl7 2>>packageErr.log
sudo apt-get $OPTIONS install liblua5.1-0 2>>packageErr.log
sudo apt-get $OPTIONS install liblwres60 2>>packageErr.log
sudo apt-get $OPTIONS install liblzma2 2>>packageErr.log
sudo apt-get $OPTIONS install libm17n-0 2>>packageErr.log
sudo apt-get $OPTIONS install libmagic1 2>>packageErr.log
sudo apt-get $OPTIONS install libmagickcore3 2>>packageErr.log
sudo apt-get $OPTIONS install libmagickcore3-extra 2>>packageErr.log
sudo apt-get $OPTIONS install libmagickwand3 2>>packageErr.log
sudo apt-get $OPTIONS install libmikmod2 2>>packageErr.log
sudo apt-get $OPTIONS install libmount1 2>>packageErr.log
sudo apt-get $OPTIONS install libmpc2 2>>packageErr.log
sudo apt-get $OPTIONS install libmpfr4 2>>packageErr.log
sudo apt-get $OPTIONS install libmysqlclient-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libmysqlclient16 2>>packageErr.log
sudo apt-get $OPTIONS install libmysqlcppconn-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libmysqlcppconn5 2>>packageErr.log
sudo apt-get $OPTIONS install libncurses5 2>>packageErr.log
sudo apt-get $OPTIONS install libncursesw5 2>>packageErr.log
sudo apt-get $OPTIONS install libneon27-gnutls 2>>packageErr.log
sudo apt-get $OPTIONS install libnet-daemon-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libnetpbm10 2>>packageErr.log
sudo apt-get $OPTIONS install libnewt0.52 2>>packageErr.log
sudo apt-get $OPTIONS install libnfnetlink0 2>>packageErr.log
sudo apt-get $OPTIONS install libnih-dbus1 2>>packageErr.log
sudo apt-get $OPTIONS install libnih1 2>>packageErr.log
sudo apt-get $OPTIONS install libnl3 2>>packageErr.log
sudo apt-get $OPTIONS install libnspr4 2>>packageErr.log
sudo apt-get $OPTIONS install libnss3 2>>packageErr.log
sudo apt-get $OPTIONS install libnss3-1d 2>>packageErr.log
sudo apt-get $OPTIONS install libnuma-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libnuma1 2>>packageErr.log
sudo apt-get $OPTIONS install libopenexr6 2>>packageErr.log
sudo apt-get $OPTIONS install libotf0 2>>packageErr.log
sudo apt-get $OPTIONS install libpam-modules 2>>packageErr.log
sudo apt-get $OPTIONS install libpam-modules-bin 2>>packageErr.log
sudo apt-get $OPTIONS install libpam-runtime 2>>packageErr.log
sudo apt-get $OPTIONS install libpam0g 2>>packageErr.log
sudo apt-get $OPTIONS install libpango1.0-0 2>>packageErr.log
sudo apt-get $OPTIONS install libpaper-utils 2>>packageErr.log
sudo apt-get $OPTIONS install libpaper1 2>>packageErr.log
sudo apt-get $OPTIONS install libparse-debianchangelog-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libparted0debian1 2>>packageErr.log
sudo apt-get $OPTIONS install libpathplan4 2>>packageErr.log
sudo apt-get $OPTIONS install libpcap0.8 2>>packageErr.log
sudo apt-get $OPTIONS install libpci3 2>>packageErr.log
sudo apt-get $OPTIONS install libpciaccess0 2>>packageErr.log
sudo apt-get $OPTIONS install libpcre3 2>>packageErr.log
sudo apt-get $OPTIONS install libpcre3-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libpcrecpp0 2>>packageErr.log
sudo apt-get $OPTIONS install libpcsclite1 2>>packageErr.log
sudo apt-get $OPTIONS install libpipeline1 2>>packageErr.log
sudo apt-get $OPTIONS install libpixman-1-0 2>>packageErr.log
sudo apt-get $OPTIONS install libplrpc-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libplymouth2 2>>packageErr.log
sudo apt-get $OPTIONS install libpng12-0 2>>packageErr.log
sudo apt-get $OPTIONS install libpod-plainer-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libpolkit-gobject-1-0 2>>packageErr.log
sudo apt-get $OPTIONS install libpoppler13 2>>packageErr.log
sudo apt-get $OPTIONS install libpopt0 2>>packageErr.log
sudo apt-get $OPTIONS install libpq-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libpq5 2>>packageErr.log
sudo apt-get $OPTIONS install libpython2.7 2>>packageErr.log
sudo apt-get $OPTIONS install libquadmath0 2>>packageErr.log
sudo apt-get $OPTIONS install libreadline6 2>>packageErr.log
sudo apt-get $OPTIONS install librsvg2-2 2>>packageErr.log
sudo apt-get $OPTIONS install librtmp0 2>>packageErr.log
sudo apt-get $OPTIONS install libsasl2-2 2>>packageErr.log
sudo apt-get $OPTIONS install libsasl2-modules 2>>packageErr.log
sudo apt-get $OPTIONS install libselinux1 2>>packageErr.log
sudo apt-get $OPTIONS install libsigc++-2.0-0c2a 2>>packageErr.log
sudo apt-get $OPTIONS install libslang2 2>>packageErr.log
sudo apt-get $OPTIONS install libsm6 2>>packageErr.log
sudo apt-get $OPTIONS install libsqlite3-0 2>>packageErr.log
sudo apt-get $OPTIONS install libsqlite3-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libss2 2>>packageErr.log
sudo apt-get $OPTIONS install libssl-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libssl-doc 2>>packageErr.log
sudo apt-get $OPTIONS install libssl1.0.0 2>>packageErr.log
sudo apt-get $OPTIONS install libstdc++6 2>>packageErr.log
sudo apt-get $OPTIONS install libstdc++6-4.6-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libsub-name-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libsvn1 2>>packageErr.log
sudo apt-get $OPTIONS install libswitch-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libtasn1-3 2>>packageErr.log
sudo apt-get $OPTIONS install libtcmalloc-minimal0 2>>packageErr.log
sudo apt-get $OPTIONS install libtext-charwidth-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libtext-iconv-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libtext-wrapi18n-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libthai-data 2>>packageErr.log
sudo apt-get $OPTIONS install libthai0 2>>packageErr.log
sudo apt-get $OPTIONS install libtiff4 2>>packageErr.log
sudo apt-get $OPTIONS install libtimedate-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libtinfo5 2>>packageErr.log
sudo apt-get $OPTIONS install libudev0 2>>packageErr.log
sudo apt-get $OPTIONS install libunwind7 2>>packageErr.log
sudo apt-get $OPTIONS install libunwind7-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libusb-0.1-4 2>>packageErr.log
sudo apt-get $OPTIONS install libusb-1.0-0 2>>packageErr.log
sudo apt-get $OPTIONS install libutempter0 2>>packageErr.log
sudo apt-get $OPTIONS install libuuid-perl 2>>packageErr.log
sudo apt-get $OPTIONS install libuuid1 2>>packageErr.log
sudo apt-get $OPTIONS install libwmf0.2-7 2>>packageErr.log
sudo apt-get $OPTIONS install libwrap0 2>>packageErr.log
sudo apt-get $OPTIONS install libwxbase2.8-0 2>>packageErr.log
sudo apt-get $OPTIONS install libwxgtk2.8-0 2>>packageErr.log
sudo apt-get $OPTIONS install libx11-6 2>>packageErr.log
sudo apt-get $OPTIONS install libx11-data 2>>packageErr.log
sudo apt-get $OPTIONS install libxapian22 2>>packageErr.log
sudo apt-get $OPTIONS install libxau6 2>>packageErr.log
sudo apt-get $OPTIONS install libxaw7 2>>packageErr.log
sudo apt-get $OPTIONS install libxcb-render0 2>>packageErr.log
sudo apt-get $OPTIONS install libxcb-shape0 2>>packageErr.log
sudo apt-get $OPTIONS install libxcb-shm0 2>>packageErr.log
sudo apt-get $OPTIONS install libxcb1 2>>packageErr.log
sudo apt-get $OPTIONS install libxcomposite1 2>>packageErr.log
sudo apt-get $OPTIONS install libxcursor1 2>>packageErr.log
sudo apt-get $OPTIONS install libxdamage1 2>>packageErr.log
sudo apt-get $OPTIONS install libxdmcp6 2>>packageErr.log
sudo apt-get $OPTIONS install libxext6 2>>packageErr.log
sudo apt-get $OPTIONS install libxfixes3 2>>packageErr.log
sudo apt-get $OPTIONS install libxfont1 2>>packageErr.log
sudo apt-get $OPTIONS install libxft2 2>>packageErr.log
sudo apt-get $OPTIONS install libxi6 2>>packageErr.log
sudo apt-get $OPTIONS install libxinerama1 2>>packageErr.log
sudo apt-get $OPTIONS install libxml2 2>>packageErr.log
sudo apt-get $OPTIONS install libxml2-dev 2>>packageErr.log
sudo apt-get $OPTIONS install libxmlrpc-core-c3-0 2>>packageErr.log
sudo apt-get $OPTIONS install libxmu6 2>>packageErr.log
sudo apt-get $OPTIONS install libxmuu1 2>>packageErr.log
sudo apt-get $OPTIONS install libxpm4 2>>packageErr.log
sudo apt-get $OPTIONS install libxrandr2 2>>packageErr.log
sudo apt-get $OPTIONS install libxrender1 2>>packageErr.log
sudo apt-get $OPTIONS install libxt6 2>>packageErr.log
sudo apt-get $OPTIONS install libxtst6 2>>packageErr.log
sudo apt-get $OPTIONS install libxv1 2>>packageErr.log
sudo apt-get $OPTIONS install libxxf86dga1 2>>packageErr.log
sudo apt-get $OPTIONS install libxxf86vm1 2>>packageErr.log
sudo apt-get $OPTIONS install libyaml-tiny-perl 2>>packageErr.log
sudo apt-get $OPTIONS install linux-firmware 2>>packageErr.log
sudo apt-get $OPTIONS install linux-generic 2>>packageErr.log
sudo apt-get $OPTIONS install linux-headers-3.0.0-13 2>>packageErr.log
sudo apt-get $OPTIONS install linux-headers-3.0.0-13-server 2>>packageErr.log
sudo apt-get $OPTIONS install linux-headers-server 2>>packageErr.log
sudo apt-get $OPTIONS install linux-image-3.0.0-12-generic 2>>packageErr.log
sudo apt-get $OPTIONS install linux-image-3.0.0-12-server 2>>packageErr.log
sudo apt-get $OPTIONS install linux-image-3.0.0-13-generic 2>>packageErr.log
sudo apt-get $OPTIONS install linux-image-3.0.0-13-server 2>>packageErr.log
sudo apt-get $OPTIONS install linux-image-generic 2>>packageErr.log
sudo apt-get $OPTIONS install linux-image-server 2>>packageErr.log
sudo apt-get $OPTIONS install linux-libc-dev 2>>packageErr.log
sudo apt-get $OPTIONS install linux-server 2>>packageErr.log
sudo apt-get $OPTIONS install lmodern 2>>packageErr.log
sudo apt-get $OPTIONS install locales 2>>packageErr.log
sudo apt-get $OPTIONS install lockfile-progs 2>>packageErr.log
sudo apt-get $OPTIONS install login 2>>packageErr.log
sudo apt-get $OPTIONS install logrotate 2>>packageErr.log
sudo apt-get $OPTIONS install lsb-base 2>>packageErr.log
sudo apt-get $OPTIONS install lsb-release 2>>packageErr.log
sudo apt-get $OPTIONS install lshw 2>>packageErr.log
sudo apt-get $OPTIONS install lsof 2>>packageErr.log
sudo apt-get $OPTIONS install ltrace 2>>packageErr.log
sudo apt-get $OPTIONS install luatex 2>>packageErr.log
sudo apt-get $OPTIONS install lvm2 2>>packageErr.log
sudo apt-get $OPTIONS install m17n-contrib 2>>packageErr.log
sudo apt-get $OPTIONS install m17n-db 2>>packageErr.log
sudo apt-get $OPTIONS install make 2>>packageErr.log
sudo apt-get $OPTIONS install makedev 2>>packageErr.log
sudo apt-get $OPTIONS install man-db 2>>packageErr.log
sudo apt-get $OPTIONS install manpages 2>>packageErr.log
sudo apt-get $OPTIONS install manpages-dev 2>>packageErr.log
sudo apt-get $OPTIONS install mawk 2>>packageErr.log
sudo apt-get $OPTIONS install memtest86+ 2>>packageErr.log
sudo apt-get $OPTIONS install mime-support 2>>packageErr.log
sudo apt-get $OPTIONS install mlocate 2>>packageErr.log
sudo apt-get $OPTIONS install module-init-tools 2>>packageErr.log
sudo apt-get $OPTIONS install mount 2>>packageErr.log
sudo apt-get $OPTIONS install mountall 2>>packageErr.log
sudo apt-get $OPTIONS install mtr-tiny 2>>packageErr.log
sudo apt-get $OPTIONS install multiarch-support 2>>packageErr.log
sudo apt-get $OPTIONS install mysql-client-5.1 2>>packageErr.log
sudo apt-get $OPTIONS install mysql-client-core-5.1 2>>packageErr.log
sudo apt-get $OPTIONS install mysql-common 2>>packageErr.log
sudo apt-get $OPTIONS install mysql-server 2>>packageErr.log
sudo apt-get $OPTIONS install mysql-server-5.1 2>>packageErr.log
sudo apt-get $OPTIONS install mysql-server-core-5.1 2>>packageErr.log
sudo apt-get $OPTIONS install nano 2>>packageErr.log
sudo apt-get $OPTIONS install ncurses-base 2>>packageErr.log
sudo apt-get $OPTIONS install ncurses-bin 2>>packageErr.log
sudo apt-get $OPTIONS install net-tools 2>>packageErr.log
sudo apt-get $OPTIONS install netbase 2>>packageErr.log
sudo apt-get $OPTIONS install netcat-openbsd 2>>packageErr.log
sudo apt-get $OPTIONS install netpbm 2>>packageErr.log
sudo apt-get $OPTIONS install ntfs-3g 2>>packageErr.log
sudo apt-get $OPTIONS install ntpdate 2>>packageErr.log
sudo apt-get $OPTIONS install openjdk-6-jre-headless 2>>packageErr.log
sudo apt-get $OPTIONS install openjdk-6-jre-lib 2>>packageErr.log
sudo apt-get $OPTIONS install openssh-client 2>>packageErr.log
sudo apt-get $OPTIONS install openssh-server 2>>packageErr.log
sudo apt-get $OPTIONS install openssl 2>>packageErr.log
sudo apt-get $OPTIONS install os-prober 2>>packageErr.log
sudo apt-get $OPTIONS install oss-compat 2>>packageErr.log
sudo apt-get $OPTIONS install parted 2>>packageErr.log
sudo apt-get $OPTIONS install passwd 2>>packageErr.log
sudo apt-get $OPTIONS install patch 2>>packageErr.log
sudo apt-get $OPTIONS install pciutils 2>>packageErr.log
sudo apt-get $OPTIONS install perl 2>>packageErr.log
sudo apt-get $OPTIONS install perl-base 2>>packageErr.log
sudo apt-get $OPTIONS install perl-modules 2>>packageErr.log
sudo apt-get $OPTIONS install pgf 2>>packageErr.log
sudo apt-get $OPTIONS install plymouth 2>>packageErr.log
sudo apt-get $OPTIONS install plymouth-theme-ubuntu-text 2>>packageErr.log
sudo apt-get $OPTIONS install popularity-contest 2>>packageErr.log
sudo apt-get $OPTIONS install powermgmt-base 2>>packageErr.log
sudo apt-get $OPTIONS install ppp 2>>packageErr.log
sudo apt-get $OPTIONS install pppconfig 2>>packageErr.log
sudo apt-get $OPTIONS install pppoeconf 2>>packageErr.log
sudo apt-get $OPTIONS install preview-latex-style 2>>packageErr.log
sudo apt-get $OPTIONS install procps 2>>packageErr.log
sudo apt-get $OPTIONS install prosper 2>>packageErr.log
sudo apt-get $OPTIONS install ps2eps 2>>packageErr.log
sudo apt-get $OPTIONS install psmisc 2>>packageErr.log
sudo apt-get $OPTIONS install psutils 2>>packageErr.log
sudo apt-get $OPTIONS install pump 2>>packageErr.log
sudo apt-get $OPTIONS install python 2>>packageErr.log
sudo apt-get $OPTIONS install python-apport 2>>packageErr.log
sudo apt-get $OPTIONS install python-apt 2>>packageErr.log
sudo apt-get $OPTIONS install python-apt-common 2>>packageErr.log
sudo apt-get $OPTIONS install python-cairo 2>>packageErr.log
sudo apt-get $OPTIONS install python-chardet 2>>packageErr.log
sudo apt-get $OPTIONS install python-crypto 2>>packageErr.log
sudo apt-get $OPTIONS install python-dbus 2>>packageErr.log
sudo apt-get $OPTIONS install python-debian 2>>packageErr.log
sudo apt-get $OPTIONS install python-gdbm 2>>packageErr.log
sudo apt-get $OPTIONS install python-gnupginterface 2>>packageErr.log
sudo apt-get $OPTIONS install python-gobject 2>>packageErr.log
sudo apt-get $OPTIONS install python-gobject-2 2>>packageErr.log
sudo apt-get $OPTIONS install python-gobject-cairo 2>>packageErr.log
sudo apt-get $OPTIONS install python-httplib2 2>>packageErr.log
sudo apt-get $OPTIONS install python-keyring 2>>packageErr.log
sudo apt-get $OPTIONS install python-launchpadlib 2>>packageErr.log
sudo apt-get $OPTIONS install python-lazr.restfulclient 2>>packageErr.log
sudo apt-get $OPTIONS install python-lazr.uri 2>>packageErr.log
sudo apt-get $OPTIONS install python-minimal 2>>packageErr.log
sudo apt-get $OPTIONS install python-newt 2>>packageErr.log
sudo apt-get $OPTIONS install python-oauth 2>>packageErr.log
sudo apt-get $OPTIONS install python-openssl 2>>packageErr.log
sudo apt-get $OPTIONS install python-pam 2>>packageErr.log
sudo apt-get $OPTIONS install python-pexpect 2>>packageErr.log
sudo apt-get $OPTIONS install python-pkg-resources 2>>packageErr.log
sudo apt-get $OPTIONS install python-problem-report 2>>packageErr.log
sudo apt-get $OPTIONS install python-pycurl 2>>packageErr.log
sudo apt-get $OPTIONS install python-serial 2>>packageErr.log
sudo apt-get $OPTIONS install python-setuptools 2>>packageErr.log
sudo apt-get $OPTIONS install python-simplejson 2>>packageErr.log
sudo apt-get $OPTIONS install python-smartpm 2>>packageErr.log
sudo apt-get $OPTIONS install python-support 2>>packageErr.log
sudo apt-get $OPTIONS install python-twisted-bin 2>>packageErr.log
sudo apt-get $OPTIONS install python-twisted-core 2>>packageErr.log
sudo apt-get $OPTIONS install python-wadllib 2>>packageErr.log
sudo apt-get $OPTIONS install python-xapian 2>>packageErr.log
sudo apt-get $OPTIONS install python-zope.interface 2>>packageErr.log
sudo apt-get $OPTIONS install python2.7 2>>packageErr.log
sudo apt-get $OPTIONS install python2.7-minimal 2>>packageErr.log
sudo apt-get $OPTIONS install readline-common 2>>packageErr.log
sudo apt-get $OPTIONS install rsync 2>>packageErr.log
sudo apt-get $OPTIONS install rsyslog 2>>packageErr.log
sudo apt-get $OPTIONS install screen 2>>packageErr.log
sudo apt-get $OPTIONS install sed 2>>packageErr.log
sudo apt-get $OPTIONS install sensible-utils 2>>packageErr.log
sudo apt-get $OPTIONS install sgml-base 2>>packageErr.log
sudo apt-get $OPTIONS install shared-mime-info 2>>packageErr.log
sudo apt-get $OPTIONS install ssh-import-id 2>>packageErr.log
sudo apt-get $OPTIONS install strace 2>>packageErr.log
sudo apt-get $OPTIONS install subversion 2>>packageErr.log
sudo apt-get $OPTIONS install sudo 2>>packageErr.log
sudo apt-get $OPTIONS install sysv-rc 2>>packageErr.log
sudo apt-get $OPTIONS install sysvinit-utils 2>>packageErr.log
sudo apt-get $OPTIONS install tar 2>>packageErr.log
sudo apt-get $OPTIONS install tasksel 2>>packageErr.log
sudo apt-get $OPTIONS install tasksel-data 2>>packageErr.log
sudo apt-get $OPTIONS install tcl8.4 2>>packageErr.log
sudo apt-get $OPTIONS install tcpd 2>>packageErr.log
sudo apt-get $OPTIONS install tcpdump 2>>packageErr.log
sudo apt-get $OPTIONS install tcsh 2>>packageErr.log
sudo apt-get $OPTIONS install telnet 2>>packageErr.log
sudo apt-get $OPTIONS install tex-common 2>>packageErr.log
sudo apt-get $OPTIONS install texlive-base 2>>packageErr.log
sudo apt-get $OPTIONS install texlive-binaries 2>>packageErr.log
sudo apt-get $OPTIONS install texlive-common 2>>packageErr.log
sudo apt-get $OPTIONS install texlive-doc-base 2>>packageErr.log
sudo apt-get $OPTIONS install texlive-extra-utils 2>>packageErr.log
sudo apt-get $OPTIONS install texlive-font-utils 2>>packageErr.log
sudo apt-get $OPTIONS install texlive-generic-recommended 2>>packageErr.log
sudo apt-get $OPTIONS install texlive-latex-base 2>>packageErr.log
sudo apt-get $OPTIONS install texlive-latex-base-doc 2>>packageErr.log
sudo apt-get $OPTIONS install texlive-latex-extra 2>>packageErr.log
sudo apt-get $OPTIONS install texlive-latex-extra-doc 2>>packageErr.log
sudo apt-get $OPTIONS install texlive-latex-recommended 2>>packageErr.log
sudo apt-get $OPTIONS install texlive-latex-recommended-doc 2>>packageErr.log
sudo apt-get $OPTIONS install texlive-luatex 2>>packageErr.log
sudo apt-get $OPTIONS install texlive-pictures 2>>packageErr.log
sudo apt-get $OPTIONS install texlive-pictures-doc 2>>packageErr.log
sudo apt-get $OPTIONS install texlive-pstricks 2>>packageErr.log
sudo apt-get $OPTIONS install texlive-pstricks-doc 2>>packageErr.log
sudo apt-get $OPTIONS install time 2>>packageErr.log
sudo apt-get $OPTIONS install tk8.4 2>>packageErr.log
sudo apt-get $OPTIONS install tmux 2>>packageErr.log
sudo apt-get $OPTIONS install ttf-dejavu-core 2>>packageErr.log
sudo apt-get $OPTIONS install ttf-liberation 2>>packageErr.log
sudo apt-get $OPTIONS install tzdata 2>>packageErr.log
sudo apt-get $OPTIONS install tzdata-java 2>>packageErr.log
sudo apt-get $OPTIONS install ubuntu-keyring 2>>packageErr.log
sudo apt-get $OPTIONS install ubuntu-minimal 2>>packageErr.log
sudo apt-get $OPTIONS install ubuntu-standard 2>>packageErr.log
sudo apt-get $OPTIONS install ucf 2>>packageErr.log
sudo apt-get $OPTIONS install udev 2>>packageErr.log
sudo apt-get $OPTIONS install ufw 2>>packageErr.log
sudo apt-get $OPTIONS install unzip 2>>packageErr.log
sudo apt-get $OPTIONS install update-manager-core 2>>packageErr.log
sudo apt-get $OPTIONS install upstart 2>>packageErr.log
sudo apt-get $OPTIONS install ureadahead 2>>packageErr.log
sudo apt-get $OPTIONS install usbutils 2>>packageErr.log
sudo apt-get $OPTIONS install util-linux 2>>packageErr.log
sudo apt-get $OPTIONS install uuid-dev 2>>packageErr.log
sudo apt-get $OPTIONS install uuid-runtime 2>>packageErr.log
sudo apt-get $OPTIONS install vim 2>>packageErr.log
sudo apt-get $OPTIONS install vim-common 2>>packageErr.log
sudo apt-get $OPTIONS install vim-runtime 2>>packageErr.log
sudo apt-get $OPTIONS install vim-tiny 2>>packageErr.log
sudo apt-get $OPTIONS install w3m 2>>packageErr.log
sudo apt-get $OPTIONS install wamerican 2>>packageErr.log
sudo apt-get $OPTIONS install watershed 2>>packageErr.log
sudo apt-get $OPTIONS install wbritish 2>>packageErr.log
sudo apt-get $OPTIONS install wget 2>>packageErr.log
sudo apt-get $OPTIONS install whiptail 2>>packageErr.log
sudo apt-get $OPTIONS install wireless-crda 2>>packageErr.log
sudo apt-get $OPTIONS install wireless-tools 2>>packageErr.log
sudo apt-get $OPTIONS install wpasupplicant 2>>packageErr.log
sudo apt-get $OPTIONS install x-ttcidfont-conf 2>>packageErr.log
sudo apt-get $OPTIONS install x11-common 2>>packageErr.log
sudo apt-get $OPTIONS install x11-utils 2>>packageErr.log
sudo apt-get $OPTIONS install xauth 2>>packageErr.log
sudo apt-get $OPTIONS install xaw3dg 2>>packageErr.log
sudo apt-get $OPTIONS install xbitmaps 2>>packageErr.log
sudo apt-get $OPTIONS install xfonts-encodings 2>>packageErr.log
sudo apt-get $OPTIONS install xfonts-utils 2>>packageErr.log
sudo apt-get $OPTIONS install xkb-data 2>>packageErr.log
sudo apt-get $OPTIONS install xml-core 2>>packageErr.log
sudo apt-get $OPTIONS install xterm 2>>packageErr.log
sudo apt-get $OPTIONS install xz-utils 2>>packageErr.log
sudo apt-get $OPTIONS install zlib1g 2>>packageErr.log
sudo apt-get $OPTIONS install zlib1g-dev 2>>packageErr.log
